meson: remove unknown arguments that cause fail to build
The build was failing with:
retro-gtk/meson.build:188:4:
ERROR: Got unknown keyword arguments "export_packages", "namespace"

Checking https://mesonbuild.com/Pkgconfig-module.html the arguments
"export_packages" and "namespace" are not present in pkg.generate, so
I removed them to make the build complete